version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: localnews
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"    # <— hostPort:containerPort