spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/news
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

newsapi:
  base-url: https://newsapi.org
  key: ${NEWSAPI_KEY}

openai:
  api-key: ${OPENAI_API_KEY} 