spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
  webclient:
    base-url: https://newsapi.org

logging:
  level:
    root: INFO
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    org.hibernate.SQL: DEBUG

server:
  port: ${PORT:8080}
  address: 0.0.0.0

newsapi:
  base-url: https://newsapi.org
  key: ${NEWSAPI_KEY}

openai:
  api-key: ${OPENAI_API_KEY} 