spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d15agph5pdvs73f39odg-a.frankfurt-postgres.render.com:5432/localnews?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:localnews}
    password: ${SPRING_DATASOURCE_PASSWORD:JF0ju86oSqedZ8S0AiTTkgnXA0kIyNKC}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-test-query: SELECT 1
      validation-timeout: 5000
      keepalive-time: 30000
      leak-detection-threshold: 60000
      auto-commit: true
      initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        format_sql: true
        generate_statistics: true
  webclient:
    base-url: https://newsapi.org
  retry:
    max-attempts: 3
    initial-interval: 1000
    multiplier: 2.0
    max-interval: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  server:
    port: 8080
    base-path: /actuator

logging:
  level:
    root: INFO
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.retry: DEBUG
    org.postgresql: DEBUG
    org.hibernate.engine.jdbc: DEBUG
    org.hibernate.engine.transaction: DEBUG
    org.hibernate.engine.jdbc.env: DEBUG
    org.hibernate.engine.jdbc.spi: DEBUG
    org.hibernate.engine.jdbc.batch: DEBUG
    org.hibernate.engine.jdbc.connections: DEBUG
    org.hibernate.engine.jdbc.dialect: DEBUG
    org.hibernate.engine.jdbc.env.spi: DEBUG
    org.hibernate.engine.jdbc.env.internal: DEBUG
    org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator: DEBUG

server:
  port: ${PORT:8080}
  address: 0.0.0.0
  tomcat:
    connection-timeout: 20000
    max-threads: 200
    min-spare-threads: 10
    threads:
      max: 200
      min-spare: 10
  shutdown: graceful
  error:
    include-message: always
    include-binding-errors: always

newsapi:
  base-url: https://newsapi.org
  key: ${NEWSAPI_KEY}

openai:
  api-key: ${OPENAI_API_KEY} 